# Generated by Django 4.2.7 on 2025-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('screening_result', 'Screening Result'), ('reminder', 'Reminder'), ('achievement', 'Achievement'), ('message', 'Message'), ('appointment', 'Appointment'), ('follow_up', 'Follow Up'), ('health_tip', 'Health Tip'), ('system', 'System'), ('abnormal_result', 'Abnormal Result'), ('summary', 'Summary')], max_length=30)),
                ('action', models.CharField(choices=[('view_result', 'View Result'), ('view_appointment', 'View Appointment'), ('view_achievement', 'View Achievement'), ('open_chat', 'Open Chat'), ('view_tip', 'View Tip'), ('schedule_follow_up', 'Schedule Follow Up'), ('submit_report', 'Submit Report'), ('review_abnormal_result', 'Review Abnormal Result'), ('view_summary', 'View Summary'), ('schedule_maintenance', 'Schedule Maintenance')], max_length=30)),
                ('related_id', models.CharField(blank=True, help_text='ID of related object', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='For scheduled notifications', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('category', models.CharField(blank=True, help_text='Notification category for grouping', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Item',
                'verbose_name_plural': 'Notification Items',
                'ordering': ['-timestamp', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('screening_results', models.BooleanField(default=True)),
                ('reminders', models.BooleanField(default=True)),
                ('achievements', models.BooleanField(default=True)),
                ('messages', models.BooleanField(default=True)),
                ('health_tips', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('type', models.CharField(choices=[('screening_result', 'Screening Result'), ('reminder', 'Reminder'), ('achievement', 'Achievement'), ('message', 'Message'), ('appointment', 'Appointment'), ('follow_up', 'Follow Up'), ('health_tip', 'Health Tip'), ('system', 'System'), ('abnormal_result', 'Abnormal Result'), ('summary', 'Summary')], max_length=30)),
                ('action', models.CharField(choices=[('view_result', 'View Result'), ('view_appointment', 'View Appointment'), ('view_achievement', 'View Achievement'), ('open_chat', 'Open Chat'), ('view_tip', 'View Tip'), ('schedule_follow_up', 'Schedule Follow Up'), ('submit_report', 'Submit Report'), ('review_abnormal_result', 'Review Abnormal Result'), ('view_summary', 'View Summary'), ('schedule_maintenance', 'Schedule Maintenance')], max_length=30)),
                ('variables', models.JSONField(default=list, help_text='List of variables that can be used in the template')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
        ),
    ]
