# Generated by Django 4.2.7 on 2025-09-02 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['user', 'is_read', 'timestamp'], name='notificatio_user_id_9d7c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['type', 'timestamp'], name='notificatio_type_6b80c7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['scheduled_for', 'timestamp'], name='notificatio_schedul_ed13c0_idx'),
        ),
    ]
